/**
 * Pixel SVG icon descriptor map for all 21 retro themes.
 *
 * Each entry is an array of SvgDesc objects describing the SVG children
 * to render inside a <svg viewBox="0 0 32 32"> element.
 *
 * Ported from /Downloads/retro-themes.jsx ICONS map (lines 6–153).
 * JSX-to-SvgDesc rules:
 *   <rect x="10" y="2" width="12" height="4"/>  → { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 4 } }
 *   strokeWidth → 'stroke-width' (kebab-case)
 *   fill="#ff0000" → fill: '#ff0000'
 *   opacity={0.8} → opacity: 0.8
 *
 * FOWT-SYNC: icon data is separate from theme colors — no sync requirement here.
 */

export type SvgAttr = Record<string, string | number>;
export interface SvgDesc {
  tag: string;
  attrs: SvgAttr;
}

export const ICONS: Record<string, SvgDesc[]> = {
  // ── MARIO ────────────────────────────────────────────────────────────────
  mario_home: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 4 } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 4 } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 2 } },
    { tag: 'rect', attrs: { x: 4, y: 12, width: 6, height: 4, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 10, y: 12, width: 4, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 14, y: 12, width: 4, height: 4, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 18, y: 12, width: 4, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 22, y: 12, width: 6, height: 4, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 6, y: 16, width: 20, height: 8, fill: '#cc4400' } },
    { tag: 'rect', attrs: { x: 10, y: 20, width: 5, height: 4, fill: '#ffaa88' } },
    { tag: 'rect', attrs: { x: 17, y: 20, width: 5, height: 4, fill: '#ffaa88' } },
  ],
  mario_star: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 10, y: 6, width: 12, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 20, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 4, y: 18, width: 8, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 20, y: 18, width: 8, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 2, y: 22, width: 6, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 24, y: 22, width: 6, height: 4, fill: '#ffdd00' } },
  ],
  mario_coin: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 20, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 12, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 12, y: 12, width: 8, height: 8, fill: '#ff9900' } },
    { tag: 'rect', attrs: { x: 6, y: 22, width: 20, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 10, y: 26, width: 12, height: 4, fill: '#ffcc00' } },
  ],
  mario_mush: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 2, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 6, y: 4, width: 20, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 4, y: 8, width: 24, height: 6, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 6, y: 8, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 22, y: 8, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 16, height: 8, fill: '#ffccaa' } },
    { tag: 'rect', attrs: { x: 12, y: 22, width: 4, height: 4, fill: '#cc9966' } },
    { tag: 'rect', attrs: { x: 18, y: 22, width: 4, height: 4, fill: '#cc9966' } },
  ],
  mario_flag: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 28, fill: '#888' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 10, height: 2, fill: '#00cc00' } },
    { tag: 'rect', attrs: { x: 18, y: 6, width: 10, height: 2, fill: '#00cc00' } },
    { tag: 'rect', attrs: { x: 18, y: 8, width: 10, height: 2, fill: '#00cc00' } },
    { tag: 'rect', attrs: { x: 18, y: 10, width: 10, height: 2, fill: '#00cc00' } },
    { tag: 'rect', attrs: { x: 18, y: 12, width: 8, height: 2, fill: '#00cc00' } },
    { tag: 'rect', attrs: { x: 4, y: 28, width: 24, height: 2, fill: '#888' } },
  ],

  // ── ZELDA ────────────────────────────────────────────────────────────────
  zelda_home: [
    {
      tag: 'polygon',
      attrs: { points: '16,2 28,28 4,28', fill: 'none', stroke: 'currentColor', 'stroke-width': 2 },
    },
    {
      tag: 'polygon',
      attrs: {
        points: '16,8 24,24 8,24',
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 1.5,
      },
    },
    { tag: 'polygon', attrs: { points: '16,14 20,22 12,22', fill: 'currentColor' } },
  ],
  zelda_sword: [
    { tag: 'rect', attrs: { x: 15, y: 2, width: 2, height: 20, fill: '#aaddff' } },
    { tag: 'rect', attrs: { x: 13, y: 4, width: 6, height: 2, fill: '#aaddff' } },
    { tag: 'rect', attrs: { x: 10, y: 20, width: 12, height: 3, fill: '#cc9900' } },
    { tag: 'rect', attrs: { x: 14, y: 23, width: 4, height: 7, fill: '#885500' } },
  ],
  zelda_shield: [
    { tag: 'path', attrs: { d: 'M16 2 L28 8 L28 18 L16 30 L4 18 L4 8 Z', fill: '#1a3a8f' } },
    { tag: 'path', attrs: { d: 'M16 6 L24 10 L24 18 L16 26 L8 18 L8 10 Z', fill: '#2255cc' } },
    { tag: 'polygon', attrs: { points: '16,10 20,16 16,22 12,16', fill: '#ffdd00' } },
  ],
  zelda_heart: [
    { tag: 'rect', attrs: { x: 8, y: 6, width: 4, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 20, y: 6, width: 4, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 6, y: 14, width: 20, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 16, height: 4, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 10, y: 22, width: 12, height: 2, fill: '#dd0000' } },
    { tag: 'rect', attrs: { x: 14, y: 26, width: 4, height: 2, fill: '#dd0000' } },
  ],
  zelda_rupee: [
    { tag: 'rect', attrs: { x: 12, y: 2, width: 8, height: 4, fill: '#00ddaa' } },
    { tag: 'rect', attrs: { x: 10, y: 6, width: 12, height: 4, fill: '#00ddaa' } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 12, height: 2, fill: '#00ddaa' } },
    { tag: 'rect', attrs: { x: 12, y: 12, width: 8, height: 6, fill: '#00ddaa' } },
    { tag: 'rect', attrs: { x: 14, y: 18, width: 4, height: 4, fill: '#00ddaa' } },
    { tag: 'rect', attrs: { x: 15, y: 22, width: 2, height: 6, fill: '#00ddaa' } },
  ],

  // ── CONTRA ───────────────────────────────────────────────────────────────
  contra_home: [
    { tag: 'rect', attrs: { x: 4, y: 24, width: 24, height: 4, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 6, y: 20, width: 20, height: 4, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 4, fill: '#888' } },
    { tag: 'rect', attrs: { x: 12, y: 12, width: 8, height: 4, fill: '#888' } },
    { tag: 'rect', attrs: { x: 14, y: 8, width: 4, height: 4, fill: '#888' } },
    { tag: 'rect', attrs: { x: 2, y: 26, width: 4, height: 2, fill: '#888' } },
    { tag: 'rect', attrs: { x: 26, y: 26, width: 4, height: 2, fill: '#888' } },
  ],
  contra_gun: [
    { tag: 'rect', attrs: { x: 2, y: 12, width: 20, height: 4, fill: '#888' } },
    { tag: 'rect', attrs: { x: 22, y: 10, width: 8, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 6, y: 16, width: 14, height: 4, fill: '#666' } },
    { tag: 'rect', attrs: { x: 8, y: 20, width: 8, height: 4, fill: '#666' } },
    { tag: 'rect', attrs: { x: 14, y: 24, width: 4, height: 4, fill: '#666' } },
  ],
  contra_expl: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 26, y: 6, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 2, y: 6, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 8, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 6, y: 18, width: 20, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 2, y: 22, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 26, y: 22, width: 4, height: 4, fill: '#ff6600' } },
  ],
  contra_bullet: [
    { tag: 'rect', attrs: { x: 6, y: 14, width: 16, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 22, y: 12, width: 4, height: 8, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 26, y: 13, width: 4, height: 6, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 2, y: 15, width: 4, height: 2, fill: '#ff4400' } },
  ],
  contra_skull: [
    { tag: 'rect', attrs: { x: 8, y: 4, width: 16, height: 2 } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 20, height: 12 } },
    { tag: 'rect', attrs: { x: 4, y: 8, width: 24, height: 8 } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 4, height: 4, fill: '#000' } },
    { tag: 'rect', attrs: { x: 14, y: 18, width: 4, height: 4, fill: '#000' } },
    { tag: 'rect', attrs: { x: 20, y: 18, width: 4, height: 4, fill: '#000' } },
    { tag: 'rect', attrs: { x: 8, y: 22, width: 16, height: 2 } },
    { tag: 'rect', attrs: { x: 12, y: 8, width: 4, height: 4, fill: '#000' } },
    { tag: 'rect', attrs: { x: 16, y: 8, width: 4, height: 4, fill: '#000' } },
  ],

  // ── MORTAL KOMBAT ────────────────────────────────────────────────────────
  mk_home: [
    { tag: 'polygon', attrs: { points: '16,2 30,30 2,30', fill: '#cc0000' } },
    { tag: 'polygon', attrs: { points: '16,8 26,28 6,28', fill: '#111' } },
    { tag: 'polygon', attrs: { points: '16,14 22,26 10,26', fill: '#cc0000' } },
    { tag: 'circle', attrs: { cx: 16, cy: 19, r: 2, fill: '#ffdd00' } },
  ],
  mk_fist: [
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 4, rx: 2 } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 20, height: 14, rx: 3 } },
    { tag: 'rect', attrs: { x: 4, y: 16, width: 8, height: 8, rx: 2 } },
    { tag: 'rect', attrs: { x: 18, y: 22, width: 10, height: 4, rx: 2, fill: '#cc0000' } },
  ],
  mk_dragon: [
    { tag: 'rect', attrs: { x: 2, y: 14, width: 6, height: 4, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 4, height: 12, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 12, y: 8, width: 8, height: 16, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 20, y: 10, width: 4, height: 12, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 24, y: 12, width: 6, height: 8, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 10, y: 2, width: 4, height: 4, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 18, y: 2, width: 4, height: 4, fill: '#ffaa00' } },
  ],
  mk_skull: [
    { tag: 'rect', attrs: { x: 8, y: 2, width: 16, height: 2 } },
    { tag: 'rect', attrs: { x: 6, y: 4, width: 20, height: 14 } },
    { tag: 'rect', attrs: { x: 4, y: 6, width: 24, height: 10 } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 4, height: 6 } },
    { tag: 'rect', attrs: { x: 14, y: 18, width: 4, height: 2 } },
    { tag: 'rect', attrs: { x: 20, y: 18, width: 4, height: 6 } },
    { tag: 'rect', attrs: { x: 8, y: 24, width: 16, height: 2 } },
    { tag: 'rect', attrs: { x: 10, y: 8, width: 5, height: 5, fill: '#000' } },
    { tag: 'rect', attrs: { x: 17, y: 8, width: 5, height: 5, fill: '#000' } },
    { tag: 'rect', attrs: { x: 13, y: 14, width: 6, height: 2, fill: '#000' } },
  ],
  mk_bolt: [
    { tag: 'polygon', attrs: { points: '20,2 10,18 16,18 12,30 22,14 16,14', fill: '#ffdd00' } },
  ],

  // ── STREET FIGHTER ───────────────────────────────────────────────────────
  sf_home: [
    { tag: 'circle', attrs: { cx: 16, cy: 10, r: 6, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 12, fill: '#1a44cc' } },
    { tag: 'rect', attrs: { x: 4, y: 18, width: 8, height: 10, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 20, y: 18, width: 8, height: 10, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 2, y: 26, width: 8, height: 4, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 22, y: 26, width: 8, height: 4, fill: '#ffcc88' } },
  ],
  sf_hadouken: [
    { tag: 'circle', attrs: { cx: 22, cy: 16, r: 8, fill: '#4488ff', opacity: 0.8 } },
    { tag: 'circle', attrs: { cx: 22, cy: 16, r: 5, fill: '#88ccff' } },
    { tag: 'circle', attrs: { cx: 22, cy: 16, r: 2, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 14, height: 4, fill: '#4488ff' } },
    { tag: 'rect', attrs: { x: 2, y: 12, width: 8, height: 2, fill: '#88ccff', opacity: 0.6 } },
    { tag: 'rect', attrs: { x: 2, y: 18, width: 8, height: 2, fill: '#88ccff', opacity: 0.6 } },
  ],
  sf_star: [
    {
      tag: 'polygon',
      attrs: {
        points: '16,2 20,12 30,12 22,19 25,30 16,23 7,30 10,19 2,12 12,12',
        fill: '#ffdd00',
      },
    },
  ],
  sf_trophy: [
    { tag: 'rect', attrs: { x: 8, y: 2, width: 16, height: 14, fill: '#ffcc00', rx: 2 } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 4, height: 8, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 24, y: 4, width: 4, height: 8, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 13, y: 16, width: 6, height: 6, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 9, y: 22, width: 14, height: 4, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 7, y: 26, width: 18, height: 3, fill: '#ffcc00' } },
  ],
  sf_pad: [
    { tag: 'rect', attrs: { x: 2, y: 10, width: 28, height: 14, rx: 7, fill: '#333' } },
    { tag: 'rect', attrs: { x: 6, y: 15, width: 2, height: 6, fill: '#888' } },
    { tag: 'rect', attrs: { x: 4, y: 17, width: 6, height: 2, fill: '#888' } },
    { tag: 'circle', attrs: { cx: 22, cy: 15, r: 2, fill: '#cc0000' } },
    { tag: 'circle', attrs: { cx: 26, cy: 18, r: 2, fill: '#00cc00' } },
    { tag: 'circle', attrs: { cx: 22, cy: 21, r: 2, fill: '#ffcc00' } },
    { tag: 'circle', attrs: { cx: 18, cy: 18, r: 2, fill: '#0066ff' } },
    { tag: 'rect', attrs: { x: 13, y: 17, width: 6, height: 2, rx: 1, fill: '#555' } },
  ],

  // ── PONG ─────────────────────────────────────────────────────────────────
  pong_home: [
    { tag: 'rect', attrs: { x: 2, y: 4, width: 4, height: 24, rx: 2, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 26, y: 4, width: 4, height: 24, rx: 2, fill: '#fff' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 3, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 15, y: 2, width: 2, height: 28, fill: '#fff', opacity: 0.15 } },
  ],
  pong_pad: [
    { tag: 'rect', attrs: { x: 4, y: 8, width: 4, height: 16, rx: 2, fill: 'currentColor' } },
    {
      tag: 'rect',
      attrs: { x: 10, y: 2, width: 2, height: 28, fill: 'currentColor', opacity: 0.3 },
    },
  ],
  pong_ball: [
    { tag: 'rect', attrs: { x: 12, y: 10, width: 8, height: 12, rx: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 10, y: 12, width: 12, height: 8, rx: 4, fill: 'currentColor' } },
  ],
  pong_score: [
    { tag: 'rect', attrs: { x: 6, y: 2, width: 8, height: 2 } },
    { tag: 'rect', attrs: { x: 18, y: 2, width: 8, height: 2 } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 14, y: 4, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 16, y: 4, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 26, y: 4, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 6, y: 14, width: 8, height: 2 } },
    { tag: 'rect', attrs: { x: 18, y: 14, width: 8, height: 2 } },
    { tag: 'rect', attrs: { x: 4, y: 16, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 14, y: 16, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 16, y: 16, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 26, y: 16, width: 2, height: 10 } },
    { tag: 'rect', attrs: { x: 6, y: 26, width: 8, height: 2 } },
    { tag: 'rect', attrs: { x: 18, y: 26, width: 8, height: 2 } },
  ],
  pong_cfg: [
    { tag: 'rect', attrs: { x: 2, y: 6, width: 28, height: 4, rx: 2 } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 4, rx: 2 } },
    { tag: 'rect', attrs: { x: 2, y: 22, width: 28, height: 4, rx: 2 } },
    {
      tag: 'circle',
      attrs: { cx: 10, cy: 8, r: 3, fill: '#000', stroke: 'currentColor', 'stroke-width': 1 },
    },
    {
      tag: 'circle',
      attrs: { cx: 22, cy: 16, r: 3, fill: '#000', stroke: 'currentColor', 'stroke-width': 1 },
    },
    {
      tag: 'circle',
      attrs: { cx: 14, cy: 24, r: 3, fill: '#000', stroke: 'currentColor', 'stroke-width': 1 },
    },
  ],

  // ── COMMODORE 64 ─────────────────────────────────────────────────────────
  c64_home: [
    { tag: 'rect', attrs: { x: 2, y: 4, width: 28, height: 20, rx: 2, fill: '#8B6914' } },
    { tag: 'rect', attrs: { x: 4, y: 6, width: 24, height: 16, fill: '#0000AA' } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 2, height: 2, fill: '#fff' } },
  ],
  c64_cur: [
    { tag: 'rect', attrs: { x: 4, y: 4, width: 16, height: 24, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 2, y: 28, width: 20, height: 2, fill: 'currentColor' } },
  ],
  c64_disk: [
    { tag: 'rect', attrs: { x: 4, y: 4, width: 24, height: 24, rx: 2, fill: '#c8a800' } },
    { tag: 'rect', attrs: { x: 8, y: 4, width: 8, height: 10, fill: '#333' } },
    { tag: 'rect', attrs: { x: 12, y: 6, width: 4, height: 6, fill: '#ccc' } },
    { tag: 'circle', attrs: { cx: 22, cy: 22, r: 4, fill: '#333' } },
    { tag: 'circle', attrs: { cx: 22, cy: 22, r: 2, fill: '#c8a800' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 10, height: 2, fill: '#333' } },
  ],
  c64_keys: [
    { tag: 'rect', attrs: { x: 2, y: 8, width: 28, height: 18, rx: 2, fill: '#888' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 4, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 4, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 16, y: 10, width: 4, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 22, y: 10, width: 6, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 4, y: 16, width: 6, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 12, y: 16, width: 8, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 22, y: 16, width: 6, height: 4, rx: 1, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 8, y: 22, width: 16, height: 2, rx: 1, fill: '#ccc' } },
  ],
  c64_chip: [
    { tag: 'rect', attrs: { x: 8, y: 8, width: 16, height: 16, fill: '#666' } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 12, height: 12, fill: '#444' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 4, y: 14, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 4, y: 18, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 24, y: 10, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 24, y: 14, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 24, y: 18, width: 4, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 2, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 14, y: 4, width: 2, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 2, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 10, y: 24, width: 2, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 14, y: 24, width: 2, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 18, y: 24, width: 2, height: 4, fill: 'currentColor' } },
  ],

  // ── DOS ──────────────────────────────────────────────────────────────────
  dos_home: [
    {
      tag: 'rect',
      attrs: {
        x: 2,
        y: 2,
        width: 28,
        height: 22,
        rx: 1,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
      },
    },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 24, height: 18, fill: '#000080' } },
    { tag: 'rect', attrs: { x: 6, y: 8, width: 6, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 13, y: 8, width: 2, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 6, y: 12, width: 12, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 6, y: 16, width: 4, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 11, y: 16, width: 4, height: 2, fill: '#fff' } },
    {
      tag: 'rect',
      attrs: { x: 13, y: 24, width: 6, height: 3, fill: 'currentColor', opacity: 0.6 },
    },
    {
      tag: 'rect',
      attrs: { x: 10, y: 27, width: 12, height: 2, fill: 'currentColor', opacity: 0.6 },
    },
  ],
  dos_folder: [
    { tag: 'rect', attrs: { x: 2, y: 8, width: 10, height: 3, rx: 1, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 2, y: 11, width: 28, height: 18, rx: 1, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 4, y: 13, width: 24, height: 14, fill: '#000080' } },
    { tag: 'rect', attrs: { x: 6, y: 15, width: 8, height: 2, fill: '#fff', opacity: 0.7 } },
    { tag: 'rect', attrs: { x: 6, y: 19, width: 12, height: 2, fill: '#fff', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 6, y: 23, width: 6, height: 2, fill: '#fff', opacity: 0.4 } },
  ],
  dos_prompt: [
    { tag: 'rect', attrs: { x: 2, y: 8, width: 6, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 9, y: 8, width: 2, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 12, y: 8, width: 8, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 2, y: 12, width: 4, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 7, y: 12, width: 14, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 2, y: 16, width: 10, height: 2, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 13, y: 16, width: 4, height: 2, fill: '#fff', opacity: 0.5 } },
  ],
  dos_floppy: [
    { tag: 'rect', attrs: { x: 4, y: 2, width: 24, height: 28, rx: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 8, y: 2, width: 12, height: 10, fill: '#888' } },
    { tag: 'rect', attrs: { x: 12, y: 4, width: 4, height: 6, fill: '#ccc' } },
    { tag: 'rect', attrs: { x: 6, y: 16, width: 20, height: 12, rx: 1, fill: '#888' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 16, height: 8, fill: '#999' } },
    { tag: 'rect', attrs: { x: 10, y: 20, width: 12, height: 2, fill: '#aaa' } },
  ],
  dos_bat: [
    {
      tag: 'rect',
      attrs: {
        x: 2,
        y: 6,
        width: 28,
        height: 20,
        rx: 2,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
      },
    },
    { tag: 'rect', attrs: { x: 4, y: 8, width: 4, height: 2, fill: '#ffff55' } },
    { tag: 'rect', attrs: { x: 4, y: 11, width: 6, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 4, y: 14, width: 8, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 4, y: 17, width: 5, height: 2, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 4, y: 20, width: 7, height: 2, fill: '#55ffff' } },
  ],

  // ── MACINTOSH ────────────────────────────────────────────────────────────
  mac_home: [
    { tag: 'rect', attrs: { x: 4, y: 14, width: 24, height: 16, rx: 1, fill: 'currentColor' } },
    { tag: 'polygon', attrs: { points: '16,4 2,16 30,16', fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 12, y: 20, width: 8, height: 10, fill: '#fff', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 6, height: 6, fill: '#fff', opacity: 0.2 } },
  ],
  mac_apple: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 4 } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 2, height: 2 } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 2 } },
    { tag: 'rect', attrs: { x: 6, y: 8, width: 20, height: 14 } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 10 } },
    { tag: 'rect', attrs: { x: 6, y: 22, width: 8, height: 4, rx: 1 } },
    { tag: 'rect', attrs: { x: 18, y: 22, width: 8, height: 4, rx: 1 } },
  ],
  mac_win: [
    {
      tag: 'rect',
      attrs: {
        x: 2,
        y: 4,
        width: 28,
        height: 24,
        rx: 2,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
      },
    },
    { tag: 'rect', attrs: { x: 2, y: 4, width: 28, height: 9, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 5, y: 6, width: 5, height: 5, rx: 1, fill: '#fff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 13, y: 7, width: 14, height: 1, fill: '#fff', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 13, y: 9, width: 14, height: 1, fill: '#fff', opacity: 0.3 } },
    {
      tag: 'rect',
      attrs: { x: 6, y: 17, width: 20, height: 2, fill: 'currentColor', opacity: 0.4 },
    },
    {
      tag: 'rect',
      attrs: { x: 6, y: 21, width: 14, height: 2, fill: 'currentColor', opacity: 0.3 },
    },
  ],
  mac_disk: [
    { tag: 'rect', attrs: { x: 4, y: 6, width: 24, height: 20, rx: 3, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 12, height: 2, fill: '#fff', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 8, y: 14, width: 16, height: 2, fill: '#fff', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 10, height: 2, fill: '#fff', opacity: 0.25 } },
    {
      tag: 'rect',
      attrs: { x: 22, y: 20, width: 4, height: 4, rx: 1, fill: '#fff', opacity: 0.4 },
    },
  ],
  mac_trash: [
    {
      tag: 'rect',
      attrs: { x: 10, y: 2, width: 12, height: 4, rx: 1, fill: 'currentColor', opacity: 0.6 },
    },
    { tag: 'rect', attrs: { x: 8, y: 4, width: 16, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 20, height: 22, rx: 2, fill: 'currentColor' } },
    {
      tag: 'rect',
      attrs: { x: 11, y: 10, width: 2, height: 14, rx: 1, fill: '#fff', opacity: 0.3 },
    },
    {
      tag: 'rect',
      attrs: { x: 15, y: 10, width: 2, height: 14, rx: 1, fill: '#fff', opacity: 0.3 },
    },
    {
      tag: 'rect',
      attrs: { x: 19, y: 10, width: 2, height: 14, rx: 1, fill: '#fff', opacity: 0.3 },
    },
  ],

  // ── MATRIX ───────────────────────────────────────────────────────────────
  mat_home: [
    { tag: 'rect', attrs: { x: 4, y: 4, width: 2, height: 24, fill: '#00ff41', opacity: 0.8 } },
    { tag: 'rect', attrs: { x: 10, y: 2, width: 2, height: 28, fill: '#00ff41' } },
    { tag: 'rect', attrs: { x: 16, y: 6, width: 2, height: 20, fill: '#00ff41', opacity: 0.6 } },
    { tag: 'rect', attrs: { x: 22, y: 4, width: 2, height: 24, fill: '#00ff41', opacity: 0.9 } },
    { tag: 'rect', attrs: { x: 28, y: 8, width: 2, height: 16, fill: '#00ff41', opacity: 0.5 } },
  ],
  mat_rain: [
    { tag: 'rect', attrs: { x: 6, y: 2, width: 2, height: 28, fill: '#00ff41', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 6, y: 2, width: 2, height: 8, fill: '#aaffaa' } },
    { tag: 'rect', attrs: { x: 14, y: 2, width: 2, height: 28, fill: '#00ff41', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 14, y: 10, width: 2, height: 8, fill: '#aaffaa' } },
    { tag: 'rect', attrs: { x: 22, y: 2, width: 2, height: 28, fill: '#00ff41', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 22, y: 18, width: 2, height: 8, fill: '#aaffaa' } },
  ],
  mat_eye: [
    {
      tag: 'ellipse',
      attrs: { cx: 16, cy: 16, rx: 13, ry: 8, fill: 'none', stroke: '#00ff41', 'stroke-width': 2 },
    },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 5, fill: '#00ff41', opacity: 0.8 } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 2, fill: '#003300' } },
    { tag: 'circle', attrs: { cx: 17, cy: 15, r: 1, fill: '#00ff41' } },
  ],
  mat_code: [
    { tag: 'rect', attrs: { x: 2, y: 4, width: 12, height: 2, fill: '#00ff41' } },
    { tag: 'rect', attrs: { x: 2, y: 8, width: 8, height: 2, fill: '#00ff41', opacity: 0.6 } },
    { tag: 'rect', attrs: { x: 2, y: 12, width: 14, height: 2, fill: '#00ff41' } },
    { tag: 'rect', attrs: { x: 2, y: 16, width: 6, height: 2, fill: '#00ff41', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 2, y: 20, width: 12, height: 2, fill: '#00ff41', opacity: 0.8 } },
    { tag: 'rect', attrs: { x: 18, y: 6, width: 12, height: 2, fill: '#00ff41', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 18, y: 10, width: 8, height: 2, fill: '#00ff41' } },
    { tag: 'rect', attrs: { x: 18, y: 14, width: 12, height: 2, fill: '#00ff41', opacity: 0.7 } },
    { tag: 'rect', attrs: { x: 18, y: 22, width: 12, height: 2, fill: '#00ff41', opacity: 0.9 } },
  ],
  mat_pill: [
    { tag: 'rect', attrs: { x: 6, y: 12, width: 8, height: 8, rx: 4, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 18, y: 12, width: 8, height: 8, rx: 4, fill: '#0044cc' } },
    { tag: 'rect', attrs: { x: 10, y: 14, width: 12, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 14, y: 14, width: 4, height: 4, fill: '#00ff41', opacity: 0.3 } },
  ],

  // ── MINECRAFT ────────────────────────────────────────────────────────────
  mc_home: [
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 28, fill: '#5d9b3f' } },
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 8, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 6, y: 4, width: 4, height: 4, fill: '#7a4a20' } },
    { tag: 'rect', attrs: { x: 12, y: 4, width: 4, height: 4, fill: '#7a4a20' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 4, height: 4, fill: '#7a4a20' } },
    { tag: 'rect', attrs: { x: 2, y: 10, width: 28, height: 4, fill: '#6aaa44' } },
    { tag: 'rect', attrs: { x: 6, y: 16, width: 8, height: 14, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 18, y: 20, width: 8, height: 10, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 4, height: 6, fill: '#7a4a20' } },
  ],
  mc_sword: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 4, fill: '#cccccc' } },
    { tag: 'rect', attrs: { x: 12, y: 6, width: 8, height: 4, fill: '#cccccc' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 4, height: 2, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 20, y: 10, width: 4, height: 2, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 14, y: 12, width: 4, height: 18, fill: '#8B5A2B' } },
  ],
  mc_block: [
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 28, fill: '#5d9b3f' } },
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 10, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 4, height: 4, fill: '#7a3a10', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 12, y: 4, width: 4, height: 4, fill: '#7a3a10', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 20, y: 4, width: 4, height: 4, fill: '#7a3a10', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 4, height: 4, fill: '#7a3a10', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 16, y: 6, width: 4, height: 4, fill: '#7a3a10', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 2, y: 12, width: 28, height: 2, fill: '#3d7a1f' } },
  ],
  mc_diamond: [
    { tag: 'rect', attrs: { x: 12, y: 2, width: 8, height: 4, fill: '#4aeeff' } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 4, fill: '#4aeeff' } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 20, height: 6, fill: '#4aeeff' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 4, fill: '#4aeeff' } },
    { tag: 'rect', attrs: { x: 12, y: 20, width: 8, height: 4, fill: '#4aeeff' } },
    { tag: 'rect', attrs: { x: 14, y: 24, width: 4, height: 4, fill: '#4aeeff' } },
  ],
  mc_creeper: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 8, fill: '#44aa44' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 16, height: 8, fill: '#44aa44' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 28, height: 8, fill: '#44aa44' } },
    { tag: 'rect', attrs: { x: 12, y: 4, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 12, y: 12, width: 8, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 10, y: 16, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 18, y: 16, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 16, height: 8, fill: '#44aa44' } },
  ],

  // ── POKÉMON ──────────────────────────────────────────────────────────────
  poke_home: [
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 16, r: 14, fill: 'none', stroke: 'currentColor', 'stroke-width': 2 },
    },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 4, fill: 'currentColor' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 5, fill: 'currentColor' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 3, fill: '#fff', opacity: 0.5 } },
    {
      tag: 'rect',
      attrs: { x: 2, y: 14, width: 28, height: 4, fill: 'currentColor', opacity: 0.8 },
    },
  ],
  poke_ball: [
    { tag: 'rect', attrs: { x: 4, y: 4, width: 24, height: 12, rx: 12, fill: '#ff2222' } },
    { tag: 'rect', attrs: { x: 4, y: 16, width: 24, height: 12, rx: 12, fill: '#ffffff' } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 4, fill: '#111' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 5, fill: '#fff' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 3, fill: '#ddd' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 1.5, fill: '#111' } },
  ],
  poke_bolt: [
    { tag: 'polygon', attrs: { points: '20,2 10,16 16,16 12,30 22,14 16,14', fill: '#ffee00' } },
  ],
  poke_leaf: [
    {
      tag: 'ellipse',
      attrs: { cx: 16, cy: 16, rx: 12, ry: 8, fill: '#44cc44', transform: 'rotate(-30,16,16)' },
    },
    { tag: 'line', attrs: { x1: 8, y1: 20, x2: 24, y2: 12, stroke: '#2a8a2a', 'stroke-width': 2 } },
    {
      tag: 'line',
      attrs: { x1: 12, y1: 24, x2: 20, y2: 10, stroke: '#2a8a2a', 'stroke-width': 1.5 },
    },
  ],
  poke_fire: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 6, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 4, height: 6, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 4, height: 6, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 8, y: 8, width: 16, height: 8, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 6, y: 12, width: 20, height: 8, fill: '#ff8800' } },
    { tag: 'rect', attrs: { x: 8, y: 20, width: 16, height: 6, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 12, y: 24, width: 8, height: 4, fill: '#ffcc00' } },
  ],

  // ── TETRIS ───────────────────────────────────────────────────────────────
  tet_home: [
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 28, fill: '#000' } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 6, height: 6, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 6, height: 6, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 16, y: 4, width: 6, height: 6, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 22, y: 4, width: 6, height: 6, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 16, y: 10, width: 6, height: 6, fill: '#ffff00' } },
    { tag: 'rect', attrs: { x: 22, y: 10, width: 6, height: 6, fill: '#ffff00' } },
    { tag: 'rect', attrs: { x: 16, y: 16, width: 6, height: 6, fill: '#ffff00' } },
    { tag: 'rect', attrs: { x: 10, y: 16, width: 6, height: 6, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 10, y: 22, width: 6, height: 6, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 4, y: 22, width: 6, height: 6, fill: '#0000ff' } },
    { tag: 'rect', attrs: { x: 4, y: 16, width: 6, height: 6, fill: '#0000ff' } },
  ],
  tet_I: [
    { tag: 'rect', attrs: { x: 2, y: 12, width: 6, height: 8, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 8, y: 12, width: 6, height: 8, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 14, y: 12, width: 6, height: 8, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 20, y: 12, width: 6, height: 8, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 3, y: 13, width: 4, height: 2, fill: '#88ffff', opacity: 0.5 } },
  ],
  tet_T: [
    { tag: 'rect', attrs: { x: 8, y: 8, width: 6, height: 6, fill: '#aa00ff' } },
    { tag: 'rect', attrs: { x: 14, y: 8, width: 6, height: 6, fill: '#aa00ff' } },
    { tag: 'rect', attrs: { x: 20, y: 8, width: 6, height: 6, fill: '#aa00ff' } },
    { tag: 'rect', attrs: { x: 14, y: 14, width: 6, height: 6, fill: '#aa00ff' } },
  ],
  tet_S: [
    { tag: 'rect', attrs: { x: 14, y: 8, width: 6, height: 6, fill: '#00ff00' } },
    { tag: 'rect', attrs: { x: 20, y: 8, width: 6, height: 6, fill: '#00ff00' } },
    { tag: 'rect', attrs: { x: 8, y: 14, width: 6, height: 6, fill: '#00ff00' } },
    { tag: 'rect', attrs: { x: 14, y: 14, width: 6, height: 6, fill: '#00ff00' } },
  ],
  tet_clear: [
    { tag: 'rect', attrs: { x: 2, y: 22, width: 28, height: 6, fill: '#ffffff', opacity: 0.9 } },
    { tag: 'rect', attrs: { x: 4, y: 14, width: 6, height: 6, fill: '#00ffff' } },
    { tag: 'rect', attrs: { x: 10, y: 14, width: 6, height: 6, fill: '#ffff00' } },
    { tag: 'rect', attrs: { x: 16, y: 14, width: 6, height: 6, fill: '#ff7700' } },
    { tag: 'rect', attrs: { x: 22, y: 14, width: 6, height: 6, fill: '#ff0000' } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 6, height: 6, fill: '#0000ff' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 6, height: 6, fill: '#aa00ff' } },
    { tag: 'rect', attrs: { x: 16, y: 4, width: 6, height: 6, fill: '#00ff00' } },
    { tag: 'rect', attrs: { x: 22, y: 4, width: 6, height: 6, fill: '#ff0077' } },
  ],

  // ── DUCK HUNT ────────────────────────────────────────────────────────────
  dh_home: [
    { tag: 'rect', attrs: { x: 2, y: 18, width: 28, height: 12, fill: '#5d9b3f' } },
    { tag: 'rect', attrs: { x: 2, y: 2, width: 28, height: 16, fill: '#88ccff' } },
    { tag: 'rect', attrs: { x: 4, y: 6, width: 8, height: 6, fill: '#888', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 4, height: 2, fill: '#fff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 6, height: 4, fill: '#888', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 20, y: 4, width: 4, height: 2, fill: '#fff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 12, y: 10, width: 6, height: 6, fill: '#5a3a00' } },
    { tag: 'rect', attrs: { x: 14, y: 8, width: 2, height: 2, fill: '#5a3a00' } },
    { tag: 'rect', attrs: { x: 16, y: 8, width: 4, height: 2, fill: '#cc4400' } },
    { tag: 'rect', attrs: { x: 10, y: 12, width: 2, height: 2, fill: '#fff' } },
  ],
  dh_gun: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 8, fill: '#555' } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 12, height: 6, fill: '#555' } },
    { tag: 'rect', attrs: { x: 4, y: 12, width: 6, height: 4, fill: '#666' } },
    { tag: 'rect', attrs: { x: 10, y: 16, width: 8, height: 10, fill: '#444' } },
    { tag: 'rect', attrs: { x: 6, y: 18, width: 4, height: 6, fill: '#444' } },
  ],
  dh_duck: [
    { tag: 'rect', attrs: { x: 10, y: 4, width: 12, height: 6, fill: '#5a3a00' } },
    { tag: 'rect', attrs: { x: 18, y: 2, width: 6, height: 4, fill: '#5a3a00' } },
    { tag: 'rect', attrs: { x: 22, y: 4, width: 4, height: 2, fill: '#ff8800' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 16, height: 8, fill: '#5a3a00' } },
    { tag: 'rect', attrs: { x: 6, y: 12, width: 8, height: 4, fill: '#88aaff' } },
    { tag: 'rect', attrs: { x: 16, y: 12, width: 6, height: 6, fill: '#88aaff' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 6, height: 4, fill: '#ff8800' } },
    { tag: 'rect', attrs: { x: 16, y: 18, width: 4, height: 4, fill: '#ff8800' } },
  ],
  dh_dog: [
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 10, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 12, height: 8, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 6, y: 12, width: 4, height: 6, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 22, y: 12, width: 4, height: 6, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 10, y: 6, width: 4, height: 6, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 18, y: 6, width: 4, height: 6, fill: '#cc7722' } },
    { tag: 'rect', attrs: { x: 12, y: 14, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 18, y: 14, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 14, y: 14, width: 2, height: 2, fill: '#000' } },
    { tag: 'rect', attrs: { x: 20, y: 14, width: 2, height: 2, fill: '#000' } },
  ],
  dh_target: [
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 16, r: 12, fill: 'none', stroke: '#ff2222', 'stroke-width': 2 },
    },
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 16, r: 7, fill: 'none', stroke: '#ff2222', 'stroke-width': 1.5 },
    },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 2, fill: '#ff2222' } },
    { tag: 'rect', attrs: { x: 15, y: 4, width: 2, height: 24, fill: '#ff2222', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 4, y: 15, width: 24, height: 2, fill: '#ff2222', opacity: 0.4 } },
  ],

  // ── PUNCH-OUT ────────────────────────────────────────────────────────────
  po_home: [
    { tag: 'circle', attrs: { cx: 16, cy: 10, r: 8, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 10, y: 18, width: 12, height: 12, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 6, y: 4, width: 4, height: 10, rx: 2, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 22, y: 4, width: 4, height: 10, rx: 2, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 12, y: 8, width: 4, height: 4, fill: '#000', opacity: 0.2 } },
    { tag: 'rect', attrs: { x: 18, y: 8, width: 4, height: 4, fill: '#000', opacity: 0.2 } },
    { tag: 'rect', attrs: { x: 12, y: 14, width: 8, height: 2, fill: '#fff', opacity: 0.3 } },
  ],
  po_glove: [
    { tag: 'rect', attrs: { x: 4, y: 8, width: 16, height: 14, rx: 4, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 20, y: 10, width: 8, height: 10, rx: 4, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 4, y: 18, width: 12, height: 10, rx: 2, fill: '#aa1111' } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 10, height: 4, fill: '#ff4444', opacity: 0.4 } },
  ],
  po_star: [
    {
      tag: 'polygon',
      attrs: {
        points: '16,2 19,11 28,11 21,17 23,26 16,21 9,26 11,17 4,11 13,11',
        fill: '#ffee00',
      },
    },
  ],
  po_belt: [
    { tag: 'rect', attrs: { x: 2, y: 10, width: 28, height: 12, fill: '#cc8800' } },
    { tag: 'rect', attrs: { x: 4, y: 12, width: 24, height: 8, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 12, y: 10, width: 8, height: 12, fill: '#cc8800' } },
    { tag: 'rect', attrs: { x: 14, y: 12, width: 4, height: 8, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 15, y: 13, width: 2, height: 6, fill: '#cc8800' } },
  ],
  po_ko: [
    { tag: 'rect', attrs: { x: 4, y: 6, width: 6, height: 20, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 4, y: 6, width: 8, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 4, y: 22, width: 8, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 10, y: 8, width: 4, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 10, y: 20, width: 4, height: 4, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 14, y: 12, width: 4, height: 8, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 18, y: 6, width: 10, height: 20, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 20, y: 8, width: 6, height: 4, fill: '#000', opacity: 0.3 } },
    { tag: 'rect', attrs: { x: 20, y: 20, width: 6, height: 4, fill: '#000', opacity: 0.3 } },
  ],

  // ── DRAGON BALL Z ────────────────────────────────────────────────────────
  dbz_home: [
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 13, fill: '#ff6600' } },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 10, fill: '#ffaa00' } },
    { tag: 'circle', attrs: { cx: 10, cy: 12, r: 2, fill: '#ff2200' } },
    { tag: 'circle', attrs: { cx: 18, cy: 8, r: 2, fill: '#ff2200' } },
    { tag: 'circle', attrs: { cx: 22, cy: 16, r: 2, fill: '#ff2200' } },
    { tag: 'circle', attrs: { cx: 16, cy: 22, r: 2, fill: '#ff2200' } },
    { tag: 'circle', attrs: { cx: 10, cy: 20, r: 2, fill: '#ff2200' } },
    { tag: 'circle', attrs: { cx: 16, cy: 4, r: 2, fill: '#000', opacity: 0.15 } },
  ],
  dbz_blast: [
    { tag: 'rect', attrs: { x: 12, y: 2, width: 8, height: 8, fill: '#ffee00', opacity: 0.9 } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 16, height: 6, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 8, fill: '#ff9900' } },
    { tag: 'rect', attrs: { x: 2, y: 14, width: 28, height: 6, fill: '#ff7700' } },
    { tag: 'rect', attrs: { x: 6, y: 20, width: 20, height: 6, fill: '#ff5500' } },
    { tag: 'rect', attrs: { x: 10, y: 24, width: 12, height: 4, fill: '#ff3300' } },
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 4, fill: '#ffffff', opacity: 0.7 } },
  ],
  dbz_hair: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 4, fill: '#ffee00' } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 20, height: 4, fill: '#ffee00' } },
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 14, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 2, y: 8, width: 4, height: 8, fill: '#ffee00' } },
    { tag: 'rect', attrs: { x: 26, y: 8, width: 4, height: 8, fill: '#ffee00' } },
    { tag: 'rect', attrs: { x: 8, y: 12, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 20, y: 12, width: 4, height: 4, fill: '#222' } },
    { tag: 'rect', attrs: { x: 10, y: 20, width: 12, height: 2, fill: '#cc7733' } },
  ],
  dbz_dragon: [
    { tag: 'rect', attrs: { x: 4, y: 14, width: 24, height: 4, fill: '#00aa44' } },
    { tag: 'rect', attrs: { x: 2, y: 10, width: 6, height: 12, rx: 3, fill: '#00aa44' } },
    { tag: 'rect', attrs: { x: 24, y: 10, width: 6, height: 12, rx: 3, fill: '#00aa44' } },
    { tag: 'rect', attrs: { x: 2, y: 6, width: 8, height: 8, fill: '#00aa44' } },
    { tag: 'rect', attrs: { x: 4, y: 4, width: 6, height: 4, fill: '#00cc55' } },
    { tag: 'rect', attrs: { x: 6, y: 2, width: 6, height: 4, fill: '#00aa44' } },
    { tag: 'rect', attrs: { x: 4, y: 6, width: 4, height: 4, fill: '#ffdd00' } },
    { tag: 'rect', attrs: { x: 6, y: 8, width: 2, height: 2, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 2, y: 8, width: 4, height: 2, fill: '#00cc55' } },
  ],
  dbz_saiyan: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 10, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 8, y: 4, width: 4, height: 8, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 20, y: 4, width: 4, height: 8, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 6, y: 12, width: 20, height: 4, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 4, y: 8, width: 4, height: 14, fill: '#cc4400' } },
    { tag: 'rect', attrs: { x: 24, y: 8, width: 4, height: 14, fill: '#cc4400' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 12, fill: '#cc4400' } },
    { tag: 'rect', attrs: { x: 10, y: 8, width: 3, height: 3, fill: '#222' } },
    { tag: 'rect', attrs: { x: 19, y: 8, width: 3, height: 3, fill: '#222' } },
  ],

  // ── ASTRO BOY ────────────────────────────────────────────────────────────
  ab_home: [
    { tag: 'circle', attrs: { cx: 16, cy: 12, r: 10, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 8, y: 4, width: 4, height: 6, fill: '#000' } },
    { tag: 'rect', attrs: { x: 20, y: 4, width: 4, height: 6, fill: '#000' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 12, height: 4, fill: '#000' } },
    { tag: 'rect', attrs: { x: 12, y: 8, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 18, y: 8, width: 4, height: 4, fill: '#fff' } },
    { tag: 'rect', attrs: { x: 13, y: 9, width: 2, height: 2, fill: '#000' } },
    { tag: 'rect', attrs: { x: 19, y: 9, width: 2, height: 2, fill: '#000' } },
    { tag: 'rect', attrs: { x: 10, y: 18, width: 12, height: 12, fill: '#000' } },
    { tag: 'rect', attrs: { x: 8, y: 20, width: 4, height: 8, rx: 2, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 20, y: 20, width: 4, height: 8, rx: 2, fill: '#ffcc88' } },
  ],
  ab_rocket: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 6, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 10, y: 8, width: 12, height: 16, fill: '#888' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 4, height: 8, fill: '#777' } },
    { tag: 'rect', attrs: { x: 20, y: 10, width: 4, height: 8, fill: '#777' } },
    { tag: 'rect', attrs: { x: 10, y: 24, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 18, y: 24, width: 4, height: 4, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 12, y: 26, width: 8, height: 4, fill: '#ff8800' } },
    { tag: 'rect', attrs: { x: 12, y: 10, width: 8, height: 6, fill: '#aae0ff', opacity: 0.6 } },
  ],
  ab_atom: [
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 4, fill: 'currentColor' } },
    {
      tag: 'ellipse',
      attrs: {
        cx: 16,
        cy: 16,
        rx: 14,
        ry: 5,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 1.5,
      },
    },
    {
      tag: 'ellipse',
      attrs: {
        cx: 16,
        cy: 16,
        rx: 14,
        ry: 5,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 1.5,
        transform: 'rotate(60,16,16)',
      },
    },
    {
      tag: 'ellipse',
      attrs: {
        cx: 16,
        cy: 16,
        rx: 14,
        ry: 5,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 1.5,
        transform: 'rotate(120,16,16)',
      },
    },
  ],
  ab_fist: [
    { tag: 'rect', attrs: { x: 8, y: 8, width: 16, height: 12, rx: 4, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 6, y: 10, width: 6, height: 8, rx: 2, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 8, y: 6, width: 4, height: 4, rx: 1, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 14, y: 6, width: 4, height: 4, rx: 1, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 20, y: 6, width: 4, height: 4, rx: 1, fill: '#ffcc88' } },
    { tag: 'rect', attrs: { x: 8, y: 18, width: 16, height: 8, rx: 2, fill: '#000' } },
  ],
  ab_star: [
    {
      tag: 'polygon',
      attrs: {
        points: '16,2 20,12 30,12 22,19 25,30 16,23 7,30 10,19 2,12 12,12',
        fill: '#ffee44',
      },
    },
  ],

  // ── FULLMETAL ALCHEMIST ──────────────────────────────────────────────────
  fma_home: [
    { tag: 'rect', attrs: { x: 4, y: 4, width: 24, height: 24, fill: '#cc3300' } },
    { tag: 'rect', attrs: { x: 8, y: 8, width: 16, height: 16, fill: '#ff5500' } },
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 10, y: 26, width: 12, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 2, y: 10, width: 4, height: 12, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 26, y: 10, width: 4, height: 12, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 12, y: 12, width: 8, height: 8, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 14, y: 10, width: 4, height: 12, fill: '#cc3300' } },
    { tag: 'rect', attrs: { x: 10, y: 14, width: 12, height: 4, fill: '#cc3300' } },
  ],
  fma_arm: [
    { tag: 'rect', attrs: { x: 12, y: 2, width: 8, height: 4, fill: '#aaaaaa' } },
    { tag: 'rect', attrs: { x: 10, y: 6, width: 12, height: 8, fill: '#888' } },
    { tag: 'rect', attrs: { x: 8, y: 14, width: 16, height: 8, fill: '#999' } },
    { tag: 'rect', attrs: { x: 10, y: 22, width: 4, height: 8, fill: '#888' } },
    { tag: 'rect', attrs: { x: 18, y: 22, width: 4, height: 8, fill: '#888' } },
    { tag: 'rect', attrs: { x: 12, y: 6, width: 4, height: 4, fill: '#bbb', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 10, y: 14, width: 12, height: 2, fill: '#777' } },
    { tag: 'rect', attrs: { x: 10, y: 18, width: 12, height: 2, fill: '#777' } },
  ],
  fma_array: [
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 16, r: 13, fill: 'none', stroke: 'currentColor', 'stroke-width': 1.5 },
    },
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 16, r: 8, fill: 'none', stroke: 'currentColor', 'stroke-width': 1 },
    },
    {
      tag: 'polygon',
      attrs: {
        points: '16,4 19,13 28,13 21,19 23,28 16,23 9,28 11,19 4,13 13,13',
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 1,
      },
    },
    { tag: 'circle', attrs: { cx: 16, cy: 16, r: 2, fill: 'currentColor' } },
  ],
  fma_flame: [
    { tag: 'rect', attrs: { x: 14, y: 2, width: 4, height: 8, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 10, y: 4, width: 4, height: 8, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 18, y: 4, width: 4, height: 8, fill: '#ff4400' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 16, height: 6, fill: '#ff6600' } },
    { tag: 'rect', attrs: { x: 6, y: 14, width: 20, height: 6, fill: '#ff8800' } },
    { tag: 'rect', attrs: { x: 8, y: 20, width: 16, height: 6, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 12, y: 24, width: 8, height: 4, fill: '#ffcc00' } },
  ],
  fma_gate: [
    {
      tag: 'rect',
      attrs: {
        x: 8,
        y: 2,
        width: 16,
        height: 28,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
      },
    },
    {
      tag: 'rect',
      attrs: { x: 12, y: 2, width: 8, height: 14, fill: 'currentColor', opacity: 0.2 },
    },
    {
      tag: 'rect',
      attrs: { x: 10, y: 4, width: 2, height: 26, fill: 'currentColor', opacity: 0.3 },
    },
    {
      tag: 'rect',
      attrs: { x: 20, y: 4, width: 2, height: 26, fill: 'currentColor', opacity: 0.3 },
    },
    { tag: 'rect', attrs: { x: 8, y: 14, width: 16, height: 2, fill: 'currentColor' } },
    {
      tag: 'circle',
      attrs: { cx: 16, cy: 8, r: 4, fill: 'none', stroke: 'currentColor', 'stroke-width': 1.5 },
    },
    { tag: 'circle', attrs: { cx: 16, cy: 8, r: 2, fill: 'currentColor', opacity: 0.5 } },
  ],

  // ── TMNT ─────────────────────────────────────────────────────────────────
  tmnt_pizza: [
    { tag: 'polygon', attrs: { points: '16,2 30,28 2,28', fill: '#f5c842' } },
    { tag: 'polygon', attrs: { points: '16,6 27,26 5,26', fill: '#e8a020' } },
    { tag: 'rect', attrs: { x: 10, y: 18, width: 4, height: 4, fill: '#cc3300', rx: 2 } },
    { tag: 'rect', attrs: { x: 17, y: 14, width: 4, height: 4, fill: '#cc3300', rx: 2 } },
    { tag: 'rect', attrs: { x: 13, y: 22, width: 3, height: 3, fill: '#44aa44', rx: 1 } },
    { tag: 'rect', attrs: { x: 8, y: 14, width: 3, height: 3, fill: '#44aa44', rx: 1 } },
    { tag: 'rect', attrs: { x: 20, y: 20, width: 3, height: 3, fill: '#cc3300', rx: 1 } },
  ],
  tmnt_mask: [
    { tag: 'rect', attrs: { x: 4, y: 10, width: 24, height: 14, rx: 7, fill: '#44aa44' } },
    { tag: 'rect', attrs: { x: 2, y: 12, width: 28, height: 10, rx: 5, fill: '#55cc55' } },
    { tag: 'rect', attrs: { x: 10, y: 13, width: 5, height: 6, fill: '#111', rx: 2 } },
    { tag: 'rect', attrs: { x: 17, y: 13, width: 5, height: 6, fill: '#111', rx: 2 } },
    { tag: 'rect', attrs: { x: 22, y: 14, width: 8, height: 4, fill: '#55cc55' } },
    { tag: 'rect', attrs: { x: 25, y: 12, width: 5, height: 8, rx: 2, fill: '#44aa44' } },
  ],
  tmnt_nunchaku: [
    { tag: 'rect', attrs: { x: 12, y: 2, width: 4, height: 12, rx: 2, fill: '#8B5A2B' } },
    { tag: 'rect', attrs: { x: 12, y: 14, width: 4, height: 4, fill: '#888' } },
    { tag: 'rect', attrs: { x: 14, y: 18, width: 2, height: 4, fill: '#aaa' } },
    { tag: 'rect', attrs: { x: 13, y: 22, width: 4, height: 10, rx: 2, fill: '#8B5A2B' } },
  ],
  tmnt_sai: [
    { tag: 'rect', attrs: { x: 15, y: 2, width: 2, height: 22, fill: '#aaa' } },
    {
      tag: 'rect',
      attrs: { x: 10, y: 10, width: 5, height: 2, fill: '#aaa', transform: 'rotate(-30,12,11)' },
    },
    {
      tag: 'rect',
      attrs: { x: 17, y: 10, width: 5, height: 2, fill: '#aaa', transform: 'rotate(30,20,11)' },
    },
    { tag: 'rect', attrs: { x: 14, y: 24, width: 4, height: 6, rx: 1, fill: '#8B5A2B' } },
  ],
  tmnt_shell: [
    { tag: 'ellipse', attrs: { cx: 16, cy: 16, rx: 13, ry: 11, fill: '#5a8a22' } },
    { tag: 'ellipse', attrs: { cx: 16, cy: 16, rx: 10, ry: 8, fill: '#7acc33' } },
    { tag: 'polygon', attrs: { points: '16,8 20,13 16,18 12,13', fill: '#5a8a22' } },
    { tag: 'polygon', attrs: { points: '10,11 15,13 13,18 8,16', fill: '#5a8a22' } },
    { tag: 'polygon', attrs: { points: '22,11 17,13 19,18 24,16', fill: '#5a8a22' } },
    { tag: 'polygon', attrs: { points: '11,19 15,17 16,22 12,23', fill: '#5a8a22' } },
    { tag: 'polygon', attrs: { points: '21,19 17,17 16,22 20,23', fill: '#5a8a22' } },
  ],

  // ── G.I. JOE ─────────────────────────────────────────────────────────────
  gij_dog: [
    {
      tag: 'rect',
      attrs: {
        x: 10,
        y: 2,
        width: 12,
        height: 16,
        rx: 6,
        fill: 'none',
        stroke: 'currentColor',
        'stroke-width': 2,
      },
    },
    { tag: 'rect', attrs: { x: 13, y: 6, width: 6, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 13, y: 10, width: 6, height: 2, fill: 'currentColor' } },
    { tag: 'rect', attrs: { x: 13, y: 14, width: 4, height: 2, fill: 'currentColor' } },
    {
      tag: 'rect',
      attrs: { x: 15, y: 18, width: 2, height: 4, fill: 'currentColor', opacity: 0.5 },
    },
    {
      tag: 'rect',
      attrs: { x: 14, y: 22, width: 4, height: 8, rx: 1, fill: 'currentColor', opacity: 0.4 },
    },
  ],
  gij_helmet: [
    { tag: 'ellipse', attrs: { cx: 16, cy: 12, rx: 13, ry: 10, fill: '#4a6a30' } },
    { tag: 'rect', attrs: { x: 3, y: 12, width: 26, height: 6, fill: '#4a6a30' } },
    { tag: 'rect', attrs: { x: 5, y: 14, width: 22, height: 4, fill: '#3a5a20' } },
    { tag: 'rect', attrs: { x: 8, y: 16, width: 16, height: 2, fill: '#2a4a10', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 6, y: 8, width: 4, height: 6, fill: '#3a5a20', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 22, y: 8, width: 4, height: 6, fill: '#3a5a20', opacity: 0.4 } },
  ],
  gij_rifle: [
    { tag: 'rect', attrs: { x: 2, y: 14, width: 24, height: 4, fill: '#555' } },
    { tag: 'rect', attrs: { x: 26, y: 12, width: 4, height: 2, fill: '#666' } },
    { tag: 'rect', attrs: { x: 2, y: 18, width: 8, height: 4, fill: '#444' } },
    { tag: 'rect', attrs: { x: 10, y: 16, width: 12, height: 6, fill: '#444' } },
    { tag: 'rect', attrs: { x: 16, y: 12, width: 4, height: 2, fill: '#666' } },
    { tag: 'rect', attrs: { x: 6, y: 18, width: 4, height: 6, fill: '#333' } },
  ],
  gij_cobra: [
    { tag: 'ellipse', attrs: { cx: 16, cy: 10, rx: 8, ry: 6, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 12, y: 14, width: 8, height: 10, fill: '#cc0000' } },
    { tag: 'rect', attrs: { x: 8, y: 10, width: 6, height: 8, rx: 3, fill: '#aa0000' } },
    { tag: 'rect', attrs: { x: 18, y: 10, width: 6, height: 8, rx: 3, fill: '#aa0000' } },
    { tag: 'rect', attrs: { x: 13, y: 16, width: 3, height: 6, fill: '#aa0000' } },
    { tag: 'rect', attrs: { x: 16, y: 16, width: 3, height: 6, fill: '#880000' } },
    { tag: 'rect', attrs: { x: 14, y: 8, width: 2, height: 4, fill: '#ffaa00' } },
    { tag: 'rect', attrs: { x: 16, y: 8, width: 2, height: 4, fill: '#ffaa00' } },
  ],
  gij_jet: [
    { tag: 'polygon', attrs: { points: '16,2 28,22 16,18 4,22', fill: '#4a6a30' } },
    { tag: 'rect', attrs: { x: 12, y: 18, width: 8, height: 8, fill: '#3a5a20' } },
    { tag: 'rect', attrs: { x: 6, y: 14, width: 6, height: 4, fill: '#3a5a20' } },
    { tag: 'rect', attrs: { x: 20, y: 14, width: 6, height: 4, fill: '#3a5a20' } },
    { tag: 'rect', attrs: { x: 14, y: 4, width: 4, height: 6, fill: '#5a7a40', opacity: 0.5 } },
  ],

  // ── TRANSFORMERS ─────────────────────────────────────────────────────────
  tf_autobot: [
    {
      tag: 'polygon',
      attrs: { points: '16,2 20,8 28,8 22,14 24,22 16,18 8,22 10,14 4,8 12,8', fill: '#cc0000' },
    },
    { tag: 'rect', attrs: { x: 13, y: 10, width: 6, height: 2, fill: '#ff6666' } },
    { tag: 'rect', attrs: { x: 11, y: 12, width: 10, height: 2, fill: '#ff6666' } },
    { tag: 'rect', attrs: { x: 13, y: 14, width: 6, height: 2, fill: '#ff6666' } },
  ],
  tf_decepticon: [
    {
      tag: 'polygon',
      attrs: { points: '16,4 22,10 28,8 24,16 28,24 16,20 4,24 8,16 4,8 10,10', fill: '#7700aa' },
    },
    { tag: 'rect', attrs: { x: 13, y: 10, width: 6, height: 2, fill: '#cc66ff' } },
    { tag: 'rect', attrs: { x: 11, y: 13, width: 10, height: 3, fill: '#cc66ff' } },
    { tag: 'rect', attrs: { x: 14, y: 16, width: 4, height: 2, fill: '#cc66ff' } },
  ],
  tf_robot: [
    { tag: 'rect', attrs: { x: 10, y: 2, width: 12, height: 10, rx: 1, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 8, y: 4, width: 4, height: 8, rx: 1, fill: '#1144cc' } },
    { tag: 'rect', attrs: { x: 20, y: 4, width: 4, height: 8, rx: 1, fill: '#1144cc' } },
    { tag: 'rect', attrs: { x: 8, y: 12, width: 16, height: 12, fill: '#cc2222' } },
    { tag: 'rect', attrs: { x: 12, y: 14, width: 8, height: 6, fill: '#1144cc' } },
    { tag: 'rect', attrs: { x: 6, y: 14, width: 4, height: 10, rx: 1, fill: '#1144cc' } },
    { tag: 'rect', attrs: { x: 22, y: 14, width: 4, height: 10, rx: 1, fill: '#1144cc' } },
    { tag: 'rect', attrs: { x: 10, y: 24, width: 4, height: 6, fill: '#888' } },
    { tag: 'rect', attrs: { x: 18, y: 24, width: 4, height: 6, fill: '#888' } },
    { tag: 'rect', attrs: { x: 12, y: 6, width: 8, height: 4, fill: '#ffcc00' } },
    { tag: 'rect', attrs: { x: 13, y: 7, width: 3, height: 2, fill: '#88ccff' } },
    { tag: 'rect', attrs: { x: 17, y: 7, width: 3, height: 2, fill: '#88ccff' } },
  ],
  tf_truck: [
    { tag: 'rect', attrs: { x: 2, y: 10, width: 28, height: 18, rx: 2, fill: '#cc2222' } },
    {
      tag: 'rect',
      attrs: { x: 4, y: 12, width: 12, height: 10, rx: 1, fill: '#88ccff', opacity: 0.7 },
    },
    { tag: 'rect', attrs: { x: 18, y: 14, width: 10, height: 8, fill: '#aa1111' } },
    { tag: 'rect', attrs: { x: 4, y: 22, width: 8, height: 4, rx: 2, fill: '#333' } },
    { tag: 'rect', attrs: { x: 14, y: 22, width: 8, height: 4, rx: 2, fill: '#333' } },
    { tag: 'rect', attrs: { x: 22, y: 22, width: 6, height: 4, rx: 2, fill: '#333' } },
    { tag: 'rect', attrs: { x: 2, y: 8, width: 28, height: 4, fill: '#aa1111' } },
    { tag: 'rect', attrs: { x: 20, y: 12, width: 8, height: 4, fill: '#ffcc00' } },
  ],
  tf_energon: [
    {
      tag: 'rect',
      attrs: {
        x: 6,
        y: 6,
        width: 20,
        height: 20,
        fill: 'none',
        stroke: '#00aaff',
        'stroke-width': 2,
      },
    },
    { tag: 'rect', attrs: { x: 8, y: 8, width: 16, height: 16, fill: '#0044aa', opacity: 0.6 } },
    { tag: 'rect', attrs: { x: 10, y: 10, width: 12, height: 12, fill: '#00ccff', opacity: 0.5 } },
    { tag: 'rect', attrs: { x: 14, y: 14, width: 4, height: 4, fill: '#aaeeff' } },
    { tag: 'rect', attrs: { x: 6, y: 6, width: 4, height: 4, fill: '#00aaff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 22, y: 6, width: 4, height: 4, fill: '#00aaff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 6, y: 22, width: 4, height: 4, fill: '#00aaff', opacity: 0.4 } },
    { tag: 'rect', attrs: { x: 22, y: 22, width: 4, height: 4, fill: '#00aaff', opacity: 0.4 } },
  ],
};
